wellle/targets.vim

autoload/targets.vim
Turns out `getcmdwintype` is only available since version 7.4.392.
Close #106.
=> 106 Only call getcmdwintype if it exists

autoload/targets.vim, plugin/targets.vim
Close #117
Summary
------------
These changes were made so this plugin will work on versions of vim older than 7.4. If a version less than 7.4 is being used then visual mappings for each text object will be created instead of creating expression mappings. Repeating these text objects on earlier versions with the '.' command will also be possible if Tim Pope's repeat.vim is installed. There will be no issue if his plugin is not installed, repeating with '.' just won't work.
I got my altered code to pass your tests just fine if I was running those tests with vim version 7.4. Oddly though, when I was running those tests with vim 7.3 they would **all** fail. I looked into it for a while but couldn't figure it out. I think it has to be some issue with the startup process between those two …
=> Add support for older versions of vim

autoload/targets.vim
Close #121.
This PR makes the quote text objects respect vim's ```'quoteescape'``` option. Now, if a quote is preceded by any character in ```'quoteescape'```, it will not be considered a quote which delimits the text object.
This implementation got a bit beefier than the last one you looked at because I re-read the documentation and it said:
> When one of the characters in this option is found inside a string, the following character will be skipped.
I originally thought that the ```'quoteescape'``` option was just one character, guess not. Let me know if you notice anything I missed!
=> Respect qe option

autoload/targets.vim
Nice catch with the empty quotes in #124 by the way. I just tested it though and it looks like selecting quote text objects is now broken prior to version 7.4 because the ```\@123<!``` pattern didn't come around until then. So this PR would fix that by using the ```\@<!``` pattern if the version is wrong and your optimized pattern otherwise.
What do you think?
On a sort of unrelated note, would you mind checking out https://github.com/tommcdo/vim-exchange/issues/38 when you get a chance? No rush of course. I only mention it because wilywampa thinks that a change will be needed in targets.vim to get it to work. I kind of think the change would be better if added to exchange.vim but your opinion would be nice to hear!
=> Added backwards compatibility for regex introduced in #124

README.md, autoload/targets.vim, autoload/targets/target.vim, cheatsheet.md, doc/targets.txt, test/test3.ok, test/test3.out
Close #127 
New setting: [`g:targets_seekRanges`](https://github.com/wellle/targets.vim/blob/127-seek-ranges/README.md#gtargets_seekranges)
Full documentation: [Customize seeking](https://github.com/wellle/targets.vim/blob/127-seek-ranges/cheatsheet.md#customize-seeking)
This also changes the default seeking behavior of pair text objects to be more consistent with seeking of the other text objects. Consider this example:
```
outer (
x ( inner )
)
```
With the cursor on `x`, when typing `da(`, it would pick the outer pair surrounding the cursor:
```
outer 
```
After the change we prefer next or last text objects contained in the cursor line over multi line text objects around the cursor. Now it picks the inner pair:
```
outer (
x 
)
```
--
@chochkov: I implemented the most flexible way to …
=> 127 Customize seeking with g:targets_seekRanges

README.md, autoload/targets.vim, autoload/targets/target.vim, cheatsheet.md, doc/targets.txt
Close #133 
This PR adds new rules for seeking behavior that always prefers targets which a boundary under the cursor to make it possible to select targets like in the example described in #133.
/cc @qstrahl
=> 133 Seeking prefer targets with boundary under cursor

README.md, autoload/targets.vim, autoload/targets/target.vim, doc/targets.txt, plugin/targets.vim, test/test.vim
This PR continues #132 by replacing the initial setting `g:targets_addJumplist` with a more flexible `g:targets_jumpRanges` (similar to `g:targets_seekRanges`).
This also implicitly changes the default jumplist behavior:
- Before: Always add to jumplist, sometimes multiple times (thanks @lag13 for fixing it :+1:)
- After: Only add to jumplist when operating on distant targets, and only once
@lag13: Thanks again for fixing the jumplist behavior in the first place! Sorry for not getting back to this earlier. Do you want to have a look at the commits I added? I would appreciate any feedback on the updated setting.
@Konfekt: I tried your example from #138 with this new behavior and it works now as you expected (as it already did on #132). Do you want to try this branch and confirm?
=> Add option g:targets_jumpRanges to control jumplist behavior

autoload/targets.vim
I know this is a development branch, but I think this `echom` was left in accidentally.
=> Disable debug message

autoload/targets.vim, plugin/targets.vim
Close #145
>Create more specific mappings before more general mappings because the later fails because of uniqueness.
>Check more specific triggers before more general ones.
>That way in case of mapping conflicts we prefer the more specific one.
This also improves similar issues with triggers for tag objects.
=> 145 Make it possible to use comma as argument trigger

README.md, autoload/targets.vim, autoload/targets/target.vim, cheatsheet.md, doc/targets.txt, plugin/targets.vim, test/Makefile, test/test.vim, test/test1.ok, test/test1.out, test/test7.in, test/test7.ok, test/test7.out
This PR tries to improve quote text by improving its seeking behavior.
Stock Vim already allows you to seek into a quote text object to the right:
```vim
echo "Hello " . world
```
With the cursor on `echo` typing `ci"` seeks into the quote to change `Hello`.
targets.vim already added seeking to the left, so the same as above would also work with the cursor on `world` (which in Stock Vim doesn't work).
targets.vim also does the same for pair text objects:
```vim
return (a+b), c
```
With the cursor on `return` or `c`, type `ci(` (or `cib`) to change `a+b`.
Since pairs of braces have a direction that can be used to match each other, seeking from within pair text objects also works:
```vim
return (pair1), s, (pair2)
```
With the cursor on `s`, `cib` seeks to the right to change `pair2`.
And …
=> Improve quote text objects

README.md, cheatsheet.md, doc/targets.txt
> For always preferring targets around cursor over distant cursorline targets.
For cases like #163 and #167.
=> Add another seekRanges example to docs

doc/targets.txt
I think this should be `a&`.
PS Thanks for the sweet plugin!
=> Typo: *ar* -> *a&*

autoload/targets.vim, test/Makefile, test/test.vim, test/test2.ok, test/test2.out, test/test8.in, test/test8.ok, test/test8.out
In examples like `(((x)))` with the cursor on `x` typing `vibibib` didn't manage to properly expand the selection. This PR fixes that. (and includes some unrelated refactorings)
Close #175
=> 175 Fix expand of tight blocks

README.md, autoload/targets.vim, cheatsheet.md, doc/targets.txt, plugin/targets.vim, test/test.vim, test/test1.ok, test/test1.out, test/testM.ok, test/testM.out
As discussed in #174 they don't really serve any purpose anymore. Renamed the setting `g:targets_nlNL` to `g:targets_nl`, but the old version should still be working in order not to break compatibility. 
@nkgm: You want to have a look at the doc changes to confirm they make sense to you?
Close #174
=> 174 Deprecate N and L modifiers

plugin/targets.vim, test/test.vim, test/test3.in, test/test3.ok, test/test3.out, test/testM.ok, test/testM.out
Close #191 
Fixes issue (introduced in https://github.com/wellle/targets.vim/pull/183) related to mapping legacy setting `g:targets_nlNL` to new setting `g:targets_nl`.
Also fixes a test introduced in the same PR.
=> 191 Fix legacy fallback for g:targets_nlNL setting

autoload/targets.vim, test/Makefile
>Apparently Vim versions 7.3 and 7.4 don't manage to properly parse a[b:]
where a is a list or string and b is an index, while Vim 8 and Neovim
handle it just fine. Interestingly a[2:] works in all versions.
>
>This commit adds a space to not confuse old Vim versions, and use a[b :]
instead.
As discussed on #195.
=> Fix substring extraction in old Vim versions

autoload/targets.vim, plugin/targets.vim
Back in https://github.com/wellle/targets.vim/pull/25 we started using expression mappings for visual mode mappings. We did that to avoid breaking some use cases related to visual block mode. In https://github.com/wellle/targets.vim/issues/117 we already talked about some performance benefits it actually has. The topic of targets.vim being somewhat slow to load comes up from time to time, for example in https://redd.it/7datnj.
While working on something else (stay tuned!) I came back to this and looked into this idea again. Turns out using expression mappings for the operator-pending mode mappings was not actually very complex to get working. In fact it's not very different to what we already have for the visual mappings. I'm not sure if or why I'd never tried that, seems very obvious now …
=> Speed up plugin load times by using expression mappings

autoload/targets.vim
>So typing `I` and `A` in visual block mode works as expected with custom `g:targets_aiAI` settings.
Close #211
=> 211 Fix visual block mode handling in expression mappings

autoload/targets/factory.vim
The current test for whether GenFunc is a function is:
if GenFunc == 0
On up-to-date versions of vim, this works fine. However, on older
versions (in particular vim 7.4 with patches 0-900) this throws an
"Invalid expression" error. Rather, targets should test directly whether
GenFunc is a FunctionRef. This patch does that as recommended in `:h
type()`.
=> Fix test for whether GenFunc is a function

README.md, doc/targets.txt, plugin/targets.vim
To allow setting up `g:targets_aiAI` even when you have conflicting mappings. Feel free to comment here or on #213 if you can't get it to work. I understand this is not as convenient to set up as it should be, but I'm not aware of a nicer way to achieve this.
Close #213
=> 213 Add setting g:targets_mapped_aiAI

autoload/targets/multigen.vim
>If a range is not found in g:targets_seekRanges, don't consider it.
Before it was still considered, just with the lowest possible score, so
ranges from g:targets_seekRanges would be preferred, but it was
impossible to actually limit the ranges.
Close #227
=> 227 Only consider targets with matching seek range

README.md, autoload/targets/generator.vim, autoload/targets/multigen.vim, doc/targets.txt
>    Add setting `g:targets_gracious`
>
>    If enabled (set to `1`), both growing and seeking will work on the largest available count if a too large count is given. For example:
>
>    - `v100ab` will select the most outer block around the cursor
>    - `v100inq` will select the most distant quote to the right/down
(the last one in the file)
Close #229
=> 229 Add support for gracious growing/seeking

autoload/health/targets.vim, autoload/targets/mappings.vim, plugin/targets.vim
As suggested in https://github.com/lervag/vimtex/pull/1384#issuecomment-520750027, this PR adds a health check that can be invoked in Neovim by calling `:checkhealth`.
It checks whether there are any Vim mappings set up which conflict with targets.vim mappings.
For example, if I add this to my vimrc
```vim
autocmd User targets#mappings#user call targets#mappings#extend({
\ 'c': {'separator': [{'d':','}]}
\ })
```
and run the health check, it shows:
```
health#targets#check
========================================================================
- WARNING: Conflicting mapping found:
ac → :<C-U>call TextObjWordBasedColumn("aw")<CR>
c → {'separator': [{'d': ','}]}
- WARNING: Conflicting mapping found:
ic → :<C-U>call TextObjWordBasedColumn("iw")<CR>
c → {'separator': [{'d': ','}]}
```
As …
=> Add health check
